### PR TITLE
fix installer version crashes on win7

### PR DESCRIPTION
**Pull request by newbie-461**
This commit is not yet tested

the problem began with 127.0 (Build ID 20240608130522)

### CODE REVIEW

**Comment by the-r3dacted** [comment]
I'll try it out tomorrow or the day after

**Comment by the-r3dacted** [comment]
uh shit
I forgot rebasing majorly fucks with pull requests

**Comment by the-r3dacted** [comment]
I manually applied the changes and built. Does it work?
https://litter.catbox.moe/iw604n.zip

**Comment by newbie-461** [comment]
> I manually applied the changes and built. Does it work? https://litter.catbox.moe/iw604n.zip

Yes, it works, there are no more crashes on startup

**Comment by the-r3dacted** [comment]
https://github.com/Eclipse-Community/r3dfox/commit/52ca3f540c66371fb26fbcbafaf2aae3e941c042

**Pull request closed without merging**
